query searchStoreQuery($allowCountries: String!, $count: Int!, $country: String!, $keywords: String!, $locale: String!, $sortBy: String!, $sortDir: String!, $start: Int!, $tag: String!) {
  Catalog {
    searchStore(
      allowCountries: $allowCountries
      count: $count
      country: $country
      keywords: $keywords
      locale: $locale
      sortBy: $sortBy
      sortDir: $sortDir
      start: $start
      tag: $tag
      offerType: "BASE_GAME"
    ) {
      elements {
        title
        id
        namespace
        description
        offerType
        effectiveDate
        creationDate
        lastModifiedDate
        
        isCodeRedemptionOnly
        keyImages {
          type
          url
        }
        currentPrice
        seller {
          id
          name
        }
        productSlug
        urlSlug
        url
        tags {
          id
          name
        }
        items {
          id
          namespace
        }
        customAttributes {
          key
          value
        }
        categories {
          path
        }
        catalogNs {
          mappings {
            pageSlug
            pageType
          }
        }
        offerMappings {
          pageSlug
          pageType
        }
        developerDisplayName
        publisherDisplayName
        price(country: $country) {
          totalPrice {
            discountPrice
            originalPrice
            voucherDiscount
            discount
            currencyCode
            currencyInfo {
              decimals
            }
            fmtPrice {
              originalPrice
              discountPrice
              intermediatePrice
            }
          }
          lineOffers {
            appliedRules {
              id
            }
          }
        }
        prePurchase
        releaseDate
        pcReleaseDate
        viewableDate
        approximateReleasePlan {
          day
          month
          quarter
          year
          releaseDateType
        }
      }
      paging {
        count
        start
        total
      }
    }
  }
}